name: COBOL Check Au tom at io n

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions / setup-java@v2
      with:
        java-version: '11'
    - name: Run COBOL Check
      env :
        ZOWE_USERNAME: $ {{ secrets.ZOWE_USERNAME }}
        ZOWE_PASSWORD: $ {{ secrets.ZOWE_PASSWORD }}
      run : |
        # Here we ' ll add our commands to run co bo lch ec k
        echo " Running COBOL Check "
        # Add actual c obo lc he ck commands here
